### ISSUE TITLE
Switch TaskManager groups to generic LDAP groups

### ISSUE THREAD

**Issue by jandusek4** [apollo-business-automation/ibm-cp4ba-enterprise-deployment#17]
**Describe the solution you'd like**
I would like to get rid of Task Manager specific LDAP groups and replace them with cpadmins and cpusers

**Comment by jandusek4** [comment]
This should do
```
tm_production_setting:
         security_roles_to_group_mapping:
           task_admins:
             groups: [cpadmins]
           task_users:
             groups: [cpusers]
           task_auditors:
             groups: [cpadmins]
```
